name: CW Code Reviewer

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout private action repository
        uses: actions/checkout@v2
        with:
          repository: codeworks/cw-ai-code-reviewer
          token: ${{ secrets.GH_API_TOKEN }}

      - name: Run Code Reviewer
        uses: codeworks/cw-ai-code-reviewer@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
